export const dependencies = {
    AxisService: Symbol.for('AxisService'),
    McpService: Symbol.for('McpService'),
    AxisApiUrl: Symbol.for('AxisApiUrl'),
    ToolsDirectory: Symbol.for('ToolsDirectory'),
    ToolDiscoveryService: Symbol.for('ToolDiscoveryService'),
    CallToolResultBuilder: Symbol.for('CallToolResultBuilder'),
    Tools: Symbol.for('Tools'),
    LoggerFactory: Symbol.for('LoggerFactory'),
    LoggingLevel: Symbol.for('LoggingLevel'),
    LoggingEnvironment: Symbol.for('LoggingEnvironment'),
    LoggingDir: Symbol.for('LoggingDir'),
    LoggingName: Symbol.for('LoggingName'),
    ProtocolService: Symbol.for('ProtocolService'),
    ProtocolRepository: Symbol.for('ProtocolRepository'),
    ProtocolName: Symbol.for('ProtocolName'),
    ProtocolDir: Symbol.for('ProtocolDir'),
    ScreenshotService: Symbol.for('ScreenshotService'),
};
