export const dependencies = {
    BrowserServiceFactory: Symbol.for('BrowserServiceFactory'),
    HttpClientFactory: Symbol.for('HttpClientFactory'),
    HttpTimeout: Symbol.for('HttpTimeout'),
    McpService: Symbol.for('McpService'),
    AxisApiUrl: Symbol.for('AxisApiUrl'),
    ToolsDirectory: Symbol.for('ToolsDirectory'),
    ToolDiscoveryService: Symbol.for('ToolDiscoveryService'),
    ToolExecutor: Symbol.for('ToolExecutor'),
    ToolResultBuilderFactory: Symbol.for('ToolResultBuilderFactory'),
    CallToolResultBuilderFactory: Symbol.for('CallToolResultBuilderFactory'),
    Tools: Symbol.for('Tools'),
    LoggerFactory: Symbol.for('LoggerFactory'),
    LoggingLevel: Symbol.for('LoggingLevel'),
    LoggingEnvironment: Symbol.for('LoggingEnvironment'),
    LoggingDir: Symbol.for('LoggingDir'),
    LoggingName: Symbol.for('LoggingName'),
    ProtocolService: Symbol.for('ProtocolService'),
    ProtocolRepository: Symbol.for('ProtocolRepository'),
    ProtocolRecordBuilderFactory: Symbol.for('ProtocolRecordBuilderFactory'),
    ProtocolName: Symbol.for('ProtocolName'),
    ProtocolDir: Symbol.for('ProtocolDir'),
    ScreenshotService: Symbol.for('ScreenshotService'),
    ScreenshotRepository: Symbol.for('ScreenshotRepository'),
};
