export const dependencies = {
    BrowserServiceFactory: Symbol.for('BrowserServiceFactory'),
    HttpClientFactory: Symbol.for('HttpClientFactory'),
    BrowserDriverFactory: Symbol.for('BrowserDriverFactory'),
    HttpTimeout: Symbol.for('HttpTimeout'),
    McpService: Symbol.for('McpService'),
    AxisApiUrl: Symbol.for('AxisApiUrl'),
    ToolsDirectory: Symbol.for('ToolsDirectory'),
    ToolDiscoveryService: Symbol.for('ToolDiscoveryService'),
    ToolGroups: Symbol.for('ToolGroups'),
    ToolOutputBuilderFactory: Symbol.for('ToolOutputBuilderFactory'),
    BrowserTools: Symbol.for('BrowserTools'),
    BrowserToolService: Symbol.for('BrowserToolService'),
    LoggerFactory: Symbol.for('LoggerFactory'),
    LoggingLevel: Symbol.for('LoggingLevel'),
    LoggingEnvironment: Symbol.for('LoggingEnvironment'),
    LogDir: Symbol.for('LogDir'),
    JourneyDir: Symbol.for('JourneyDir'),
    ProtocolService: Symbol.for('ProtocolService'),
    ProtocolRepository: Symbol.for('ProtocolRepository'),
    ProtocolRecordBuilderFactory: Symbol.for('ProtocolRecordBuilderFactory'),
    BinaryService: Symbol.for('BinaryService'),
    BinaryRepository: Symbol.for('BinaryRepository'),
};
